const emptySnapshot = {
  generatedAt: "",
  skills: [],
  mcpServers: [],
  presetPaths: [],
  globalSettings: {},
};

let snapshot = normalizeSnapshot(window.SKILL_DATA || emptySnapshot);
let currentView = "skills";
let activeCategory = "全部";
let activeSource = "全部";
let selected = { skills: "", mcp: "" };
let uiLanguage = "zh-CN";
let rawMode = "original";
let currentDetailItem = null;

const languageNames = {
  "zh-CN": "简体中文",
  en: "English",
  ja: "日本語",
  ko: "한국어",
  fr: "Français",
  de: "Deutsch",
  es: "Español",
  pt: "Português",
  ru: "Русский",
  ar: "العربية",
};

uiLanguage = getInitialLanguage();

const uiText = {
  "zh-CN": {
    subtitle: "把 Codex、Claude 的 Skill 原文和 MCP 配置摊开看清楚。",
    chooseSkillDir: "选择 Skill 目录",
    chooseMcpConfig: "选择 MCP 配置",
    importSnapshot: "导入快照",
    exportJson: "导出 JSON",
    snapshotLoading: "正在读取本机快照",
    snapshotHelp: "浏览器不能自动穿透读取任意本机目录；推荐运行扫描器生成快照，或手动选择目录/配置文件。",
    skillMetric: "Skill",
    mcpMetric: "MCP",
    rawMetric: "包含原文",
    enabledMcpMetric: "启用 MCP",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "搜索",
    category: "分类",
    source: "来源",
    sort: "排序",
    skillList: "Skill 清单",
    mcpList: "MCP 配置清单",
    selectedSkill: "Selected Skill",
    selectedMcp: "Selected MCP",
    essence: "本质",
    path: "路径",
    frontmatter: "frontmatter / 元信息",
    rawSkill: "SKILL.md 原文",
    rawMcp: "MCP 原始配置",
    original: "原文",
    translated: "译文",
    copyRaw: "复制原文",
    copied: "已复制",
    translationStatus: "译文由本地内置词典生成，保留 Markdown 结构，不调用模型或网络。",
    translating: "正在生成译文...",
    translatedByDictionary: "已使用本地内置 Skill 术语词典生成阅读辅助译文，未调用模型或网络。",
    noSelection: "选择一个条目",
    noSelectionHelp: "点击左侧条目查看它的原始内容。",
  },
  en: {
    subtitle: "Inspect Codex and Claude Skill source plus MCP configuration on this computer.",
    chooseSkillDir: "Choose Skill folder",
    chooseMcpConfig: "Choose MCP config",
    importSnapshot: "Import snapshot",
    exportJson: "Export JSON",
    snapshotLoading: "Reading local snapshot",
    snapshotHelp: "The browser cannot read arbitrary local folders by itself. Run the scanner or choose folders/config files manually.",
    skillMetric: "Skills",
    mcpMetric: "MCP",
    rawMetric: "Raw files",
    enabledMcpMetric: "Enabled MCP",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "Search",
    category: "Category",
    source: "Source",
    sort: "Sort",
    skillList: "Skill list",
    mcpList: "MCP config list",
    selectedSkill: "Selected Skill",
    selectedMcp: "Selected MCP",
    essence: "Essence",
    path: "Path",
    frontmatter: "frontmatter / metadata",
    rawSkill: "SKILL.md source",
    rawMcp: "MCP raw config",
    original: "Source",
    translated: "Translation",
    copyRaw: "Copy text",
    copied: "Copied",
    translationStatus: "Translation is generated by the local built-in glossary, keeps Markdown structure, and does not call models or the network.",
    translating: "Translating...",
    translatedByDictionary: "Generated with the local built-in Skill glossary. No model or network call was made.",
    noSelection: "Select an item",
    noSelectionHelp: "Click an item on the left to inspect its raw content.",
  },
};

const languageFallbacks = {
  ja: "en",
  ko: "en",
  fr: "en",
  de: "en",
  es: "en",
  pt: "en",
  ru: "en",
  ar: "en",
};

Object.assign(uiText, {
  ja: {
    subtitle: "このコンピューター上の Codex / Claude Skill 原文と MCP 設定を確認します。",
    chooseSkillDir: "Skill フォルダー",
    chooseMcpConfig: "MCP 設定",
    importSnapshot: "スナップショット",
    exportJson: "JSON 出力",
    snapshotLoading: "ローカル情報を読み込み中",
    snapshotHelp: "スキャナーを実行するか、フォルダー/設定ファイルを選択してください。",
    skillMetric: "Skill",
    mcpMetric: "MCP",
    rawMetric: "原文あり",
    enabledMcpMetric: "有効 MCP",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "検索",
    category: "分類",
    source: "出所",
    sort: "並び替え",
    skillList: "Skill 一覧",
    mcpList: "MCP 設定一覧",
    selectedSkill: "選択中の Skill",
    selectedMcp: "選択中の MCP",
    essence: "本質",
    path: "パス",
    frontmatter: "frontmatter / メタ情報",
    rawSkill: "SKILL.md 原文",
    rawMcp: "MCP 原設定",
    original: "原文",
    translated: "翻訳",
    copyRaw: "コピー",
    copied: "コピー済み",
    translationStatus: "翻訳はローカル内蔵用語集で生成され、Markdown 構造を保ち、モデルやネットワークを呼びません。",
    translating: "翻訳中...",
    translatedByDictionary: "ローカル内蔵 Skill 用語集で補助翻訳しました。モデルやネットワークは呼びません。",
    noSelection: "項目を選択",
    noSelectionHelp: "左の項目をクリックして原文を確認します。",
  },
  ko: {
    subtitle: "이 컴퓨터의 Codex / Claude Skill 원문과 MCP 설정을 확인합니다.",
    chooseSkillDir: "Skill 폴더 선택",
    chooseMcpConfig: "MCP 설정 선택",
    importSnapshot: "스냅샷 가져오기",
    exportJson: "JSON 내보내기",
    snapshotLoading: "로컬 스냅샷 읽는 중",
    snapshotHelp: "스캐너를 실행하거나 폴더/설정 파일을 직접 선택하세요.",
    skillMetric: "Skill",
    mcpMetric: "MCP",
    rawMetric: "원문 포함",
    enabledMcpMetric: "활성 MCP",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "검색",
    category: "분류",
    source: "출처",
    sort: "정렬",
    skillList: "Skill 목록",
    mcpList: "MCP 설정 목록",
    selectedSkill: "선택한 Skill",
    selectedMcp: "선택한 MCP",
    essence: "본질",
    path: "경로",
    frontmatter: "frontmatter / 메타데이터",
    rawSkill: "SKILL.md 원문",
    rawMcp: "MCP 원본 설정",
    original: "원문",
    translated: "번역",
    copyRaw: "복사",
    copied: "복사됨",
    translationStatus: "번역은 로컬 내장 용어집으로 생성되며 Markdown 구조를 유지하고 모델이나 네트워크를 호출하지 않습니다.",
    translating: "번역 중...",
    translatedByDictionary: "로컬 내장 Skill 용어집으로 보조 번역했습니다. 모델이나 네트워크를 호출하지 않습니다.",
    noSelection: "항목 선택",
    noSelectionHelp: "왼쪽 항목을 클릭해 원본 내용을 확인하세요.",
  },
  fr: {
    subtitle: "Inspecte les Skills Codex / Claude et la configuration MCP de cet ordinateur.",
    chooseSkillDir: "Dossier Skill",
    chooseMcpConfig: "Config MCP",
    importSnapshot: "Importer",
    exportJson: "Exporter JSON",
    snapshotLoading: "Lecture locale",
    snapshotHelp: "Lancez le scanner ou choisissez un dossier/fichier de configuration.",
    skillMetric: "Skills",
    mcpMetric: "MCP",
    rawMetric: "Sources",
    enabledMcpMetric: "MCP actifs",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "Recherche",
    category: "Catégorie",
    source: "Source",
    sort: "Tri",
    skillList: "Liste des Skills",
    mcpList: "Configurations MCP",
    selectedSkill: "Skill sélectionné",
    selectedMcp: "MCP sélectionné",
    essence: "Essence",
    path: "Chemin",
    frontmatter: "frontmatter / métadonnées",
    rawSkill: "Source SKILL.md",
    rawMcp: "Configuration MCP brute",
    original: "Original",
    translated: "Traduction",
    copyRaw: "Copier",
    copied: "Copié",
    translationStatus: "La traduction utilise le glossaire local intégré, garde Markdown et n'appelle aucun modèle ni réseau.",
    translating: "Traduction...",
    translatedByDictionary: "Généré avec le glossaire Skill local intégré. Aucun modèle ni appel réseau.",
    noSelection: "Choisir un élément",
    noSelectionHelp: "Cliquez un élément à gauche pour lire son contenu brut.",
  },
  de: {
    subtitle: "Prüft Codex-/Claude-Skills und MCP-Konfiguration auf diesem Computer.",
    chooseSkillDir: "Skill-Ordner",
    chooseMcpConfig: "MCP-Konfig",
    importSnapshot: "Snapshot importieren",
    exportJson: "JSON exportieren",
    snapshotLoading: "Lokalen Snapshot lesen",
    snapshotHelp: "Scanner ausführen oder Ordner/Konfiguration manuell wählen.",
    skillMetric: "Skills",
    mcpMetric: "MCP",
    rawMetric: "Quellen",
    enabledMcpMetric: "Aktive MCP",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "Suche",
    category: "Kategorie",
    source: "Quelle",
    sort: "Sortierung",
    skillList: "Skill-Liste",
    mcpList: "MCP-Konfigurationen",
    selectedSkill: "Ausgewählter Skill",
    selectedMcp: "Ausgewähltes MCP",
    essence: "Kern",
    path: "Pfad",
    frontmatter: "frontmatter / Metadaten",
    rawSkill: "SKILL.md-Quelle",
    rawMcp: "MCP-Rohkonfig",
    original: "Original",
    translated: "Übersetzung",
    copyRaw: "Kopieren",
    copied: "Kopiert",
    translationStatus: "Die Übersetzung nutzt das lokale integrierte Glossar, behält Markdown bei und ruft kein Modell oder Netzwerk auf.",
    translating: "Übersetzen...",
    translatedByDictionary: "Mit lokalem integriertem Skill-Glossar erzeugt. Kein Modell- oder Netzwerkaufruf.",
    noSelection: "Eintrag wählen",
    noSelectionHelp: "Links einen Eintrag anklicken, um den Rohinhalt zu sehen.",
  },
  es: {
    subtitle: "Inspecciona Skills de Codex / Claude y configuración MCP en este equipo.",
    chooseSkillDir: "Carpeta Skill",
    chooseMcpConfig: "Config MCP",
    importSnapshot: "Importar",
    exportJson: "Exportar JSON",
    snapshotLoading: "Leyendo equipo local",
    snapshotHelp: "Ejecuta el escáner o elige una carpeta/archivo de configuración.",
    skillMetric: "Skills",
    mcpMetric: "MCP",
    rawMetric: "Fuentes",
    enabledMcpMetric: "MCP activos",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "Buscar",
    category: "Categoría",
    source: "Fuente",
    sort: "Ordenar",
    skillList: "Lista de Skills",
    mcpList: "Configuraciones MCP",
    selectedSkill: "Skill seleccionado",
    selectedMcp: "MCP seleccionado",
    essence: "Esencia",
    path: "Ruta",
    frontmatter: "frontmatter / metadatos",
    rawSkill: "Fuente SKILL.md",
    rawMcp: "Config MCP original",
    original: "Original",
    translated: "Traducción",
    copyRaw: "Copiar",
    copied: "Copiado",
    translationStatus: "La traducción usa el glosario local integrado, conserva Markdown y no llama a modelos ni a la red.",
    translating: "Traduciendo...",
    translatedByDictionary: "Generado con el glosario local de Skill. Sin llamadas a modelos ni a la red.",
    noSelection: "Selecciona un elemento",
    noSelectionHelp: "Haz clic en un elemento de la izquierda para ver el contenido original.",
  },
  pt: {
    subtitle: "Inspeciona Skills do Codex / Claude e configuração MCP neste computador.",
    chooseSkillDir: "Pasta Skill",
    chooseMcpConfig: "Config MCP",
    importSnapshot: "Importar",
    exportJson: "Exportar JSON",
    snapshotLoading: "Lendo dados locais",
    snapshotHelp: "Execute o scanner ou escolha uma pasta/arquivo de configuração.",
    skillMetric: "Skills",
    mcpMetric: "MCP",
    rawMetric: "Fontes",
    enabledMcpMetric: "MCP ativos",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "Buscar",
    category: "Categoria",
    source: "Origem",
    sort: "Ordenar",
    skillList: "Lista de Skills",
    mcpList: "Configurações MCP",
    selectedSkill: "Skill selecionado",
    selectedMcp: "MCP selecionado",
    essence: "Essência",
    path: "Caminho",
    frontmatter: "frontmatter / metadados",
    rawSkill: "Fonte SKILL.md",
    rawMcp: "Config MCP bruta",
    original: "Original",
    translated: "Tradução",
    copyRaw: "Copiar",
    copied: "Copiado",
    translationStatus: "A tradução usa o glossário local integrado, mantém Markdown e não chama modelos nem a rede.",
    translating: "Traduzindo...",
    translatedByDictionary: "Gerado com o glossário local de Skill. Sem chamadas a modelos ou rede.",
    noSelection: "Selecione um item",
    noSelectionHelp: "Clique em um item à esquerda para ver o conteúdo bruto.",
  },
  ru: {
    subtitle: "Просмотр исходных Skill Codex / Claude и MCP-конфигурации на этом компьютере.",
    chooseSkillDir: "Папка Skill",
    chooseMcpConfig: "MCP config",
    importSnapshot: "Импорт",
    exportJson: "Экспорт JSON",
    snapshotLoading: "Чтение локальных данных",
    snapshotHelp: "Запустите сканер или выберите папку/файл конфигурации.",
    skillMetric: "Skills",
    mcpMetric: "MCP",
    rawMetric: "Исходники",
    enabledMcpMetric: "Активные MCP",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "Поиск",
    category: "Категория",
    source: "Источник",
    sort: "Сортировка",
    skillList: "Список Skills",
    mcpList: "MCP конфигурации",
    selectedSkill: "Выбранный Skill",
    selectedMcp: "Выбранный MCP",
    essence: "Суть",
    path: "Путь",
    frontmatter: "frontmatter / метаданные",
    rawSkill: "Исходный SKILL.md",
    rawMcp: "Сырая MCP config",
    original: "Оригинал",
    translated: "Перевод",
    copyRaw: "Копировать",
    copied: "Скопировано",
    translationStatus: "Перевод создается локальным встроенным глоссарием, сохраняет Markdown и не вызывает модели или сеть.",
    translating: "Перевод...",
    translatedByDictionary: "Создано локальным встроенным глоссарием Skill. Без вызова модели или сети.",
    noSelection: "Выберите элемент",
    noSelectionHelp: "Нажмите элемент слева, чтобы увидеть исходный текст.",
  },
  ar: {
    subtitle: "افحص نصوص Codex / Claude Skill وإعدادات MCP على هذا الجهاز.",
    chooseSkillDir: "مجلد Skill",
    chooseMcpConfig: "إعداد MCP",
    importSnapshot: "استيراد",
    exportJson: "تصدير JSON",
    snapshotLoading: "قراءة البيانات المحلية",
    snapshotHelp: "شغّل الماسح أو اختر مجلدا/ملف إعدادات.",
    skillMetric: "Skill",
    mcpMetric: "MCP",
    rawMetric: "النصوص الأصلية",
    enabledMcpMetric: "MCP مفعّل",
    skillTab: "Skill",
    mcpTab: "MCP",
    search: "بحث",
    category: "الفئة",
    source: "المصدر",
    sort: "ترتيب",
    skillList: "قائمة Skill",
    mcpList: "إعدادات MCP",
    selectedSkill: "Skill المحدد",
    selectedMcp: "MCP المحدد",
    essence: "الجوهر",
    path: "المسار",
    frontmatter: "frontmatter / بيانات وصفية",
    rawSkill: "نص SKILL.md",
    rawMcp: "إعداد MCP الأصلي",
    original: "الأصل",
    translated: "ترجمة",
    copyRaw: "نسخ",
    copied: "تم النسخ",
    translationStatus: "تستخدم الترجمة القاموس المحلي المدمج وتحافظ على Markdown ولا تستدعي نموذجا أو شبكة.",
    translating: "جار الترجمة...",
    translatedByDictionary: "تم الإنشاء بقاموس Skill المحلي المدمج، دون استدعاء نموذج أو شبكة.",
    noSelection: "اختر عنصرا",
    noSelectionHelp: "انقر عنصرا من اليسار لعرض النص الأصلي.",
  },
});

const defaultPresetPaths = [
  "%USERPROFILE%\\.codex\\skills",
  "%USERPROFILE%\\.codex\\plugins\\cache",
  "%USERPROFILE%\\.codex\\config.toml",
  "%USERPROFILE%\\.claude\\skills",
  "%APPDATA%\\Claude\\claude_desktop_config.json",
  "~/.claude/settings.json",
  ".mcp.json",
];

function getInitialLanguage() {
  const saved = localStorage.getItem("seethrough-skill:language");
  if (saved && languageNames[saved]) return saved;
  const browserLanguage = navigator.language || "zh-CN";
  if (languageNames[browserLanguage]) return browserLanguage;
  const shortLanguage = browserLanguage.split("-")[0];
  return languageNames[shortLanguage] ? shortLanguage : "zh-CN";
}

function t(key) {
  const table = uiText[uiLanguage] || uiText[languageFallbacks[uiLanguage]] || uiText.en;
  return table[key] || uiText.en[key] || uiText["zh-CN"][key] || key;
}

function applyI18n() {
  document.documentElement.lang = uiLanguage;
  document.documentElement.dir = uiLanguage === "ar" ? "rtl" : "ltr";
  document.querySelector(".subtitle").textContent = t("subtitle");
  document.getElementById("chooseDirectoryBtn").textContent = t("chooseSkillDir");
  document.getElementById("loadConfigBtn").textContent = t("chooseMcpConfig");
  document.getElementById("loadSnapshotBtn").textContent = t("importSnapshot");
  document.getElementById("exportBtn").textContent = t("exportJson");
  document.getElementById("languageSelect").value = uiLanguage;
  document.querySelectorAll(".metric span")[0].textContent = t("skillMetric");
  document.querySelectorAll(".metric span")[1].textContent = t("mcpMetric");
  document.querySelectorAll(".metric span")[2].textContent = t("rawMetric");
  document.querySelectorAll(".metric span")[3].textContent = t("enabledMcpMetric");
  document.getElementById("skillsTab").textContent = t("skillTab");
  document.getElementById("mcpTab").textContent = t("mcpTab");
  document.querySelector("label[for=searchInput]").textContent = t("search");
  document.querySelectorAll(".filter-block h2")[0].textContent = t("category");
  document.querySelectorAll(".filter-block h2")[1].textContent = t("source");
  document.querySelectorAll(".filter-block h2")[2].textContent = t("sort");
  document.getElementById("detailExtraLabel")?.remove();
  document.querySelectorAll(".detail-grid dt")[0].textContent = t("essence");
  document.querySelectorAll(".detail-grid dt")[1].textContent = t("category");
  document.querySelectorAll(".detail-grid dt")[2].textContent = t("source");
  document.querySelectorAll(".detail-grid dt")[3].textContent = t("path");
  document.querySelector("#frontmatterSection h3").textContent = t("frontmatter");
  document.getElementById("rawOriginalBtn").textContent = t("original");
  document.getElementById("rawTranslatedBtn").textContent = t("translated");
  document.getElementById("copyRawBtn").textContent = t("copyRaw");
  document.getElementById("translationStatus").textContent = t("translationStatus");
}

const skillCategoryRules = [
  ["前端/浏览器", /frontend|browser|chrome|playwright|screenshot|figma|ui|ux|design|canvas/i],
  ["文档/办公", /doc|document|office|word|pdf|ppt|slide|presentation|excel|sheet|xlsx|pandoc/i],
  ["代码工程", /code|coding|testing|tdd|review|patterns|api|backend|frontend|python|java|react|node|docker|database|deploy/i],
  ["研究/知识", /research|literature|academic|pubmed|retrieval|knowledge|market|article|writing/i],
  ["安全/审计", /security|audit|risk|threat|codeql|insecure|compliance|hipaa|constant-time/i],
  ["媒体/设计", /image|photo|photoshop|video|motion|logo|figma|design|retouch|blender|manim/i],
  ["自动化/工具", /mcp|tool|automation|agent|cli|workflow|ops|browser|desktop/i],
  ["业务/行业", /billing|finance|inventory|logistics|healthcare|procurement|customer|trade|energy/i],
];

const mcpCategoryRules = [
  ["开发工具", /context7|github|serena|codegraph|node|repl|openai|docs/i],
  ["浏览器/桌面", /browser|chrome|playwright|desktop|computer/i],
  ["文件/数据", /filesystem|drive|pdf|sheets|docs|database|memory/i],
  ["账号/云服务", /gmail|google|notion|slack|linear|figma|canva|netdisk|github/i],
  ["专业软件", /photoshop|autocad|biorender|davinci|drawio|figma/i],
  ["研究检索", /search|firecrawl|exa|arxiv|pubmed|zotero|crossref/i],
];

function normalizeSnapshot(input) {
  const data = input && typeof input === "object" ? input : {};
  return {
    ...emptySnapshot,
    ...data,
    skills: Array.isArray(data.skills) ? data.skills : [],
    mcpServers: Array.isArray(data.mcpServers) ? data.mcpServers : [],
    presetPaths: Array.isArray(data.presetPaths) ? data.presetPaths : [],
    globalSettings: data.globalSettings || {},
  };
}

function skillItems() {
  const groups = countBy(snapshot.skills.map((item) => skillName(item)));
  return snapshot.skills.map((skill, index) => {
    const name = skillName(skill);
    const raw = skill.rawMarkdown || skill.rawContent || "";
    const description = skill.description || skill.frontmatter?.description || firstMarkdownHeading(raw) || "";
    const source = skill.source || skill.ecosystem || "local";
    return {
      ...skill,
      id: skill.id || stableId(["skill", name, skill.primaryPath || skill.path || index]),
      viewType: "skills",
      name,
      displayName: skill.displayName || skill.frontmatter?.name || name,
      description,
      source,
      category: skill.category || inferCategory(name, `${description}\n${raw}`, skillCategoryRules),
      rawMarkdown: raw,
      primaryPath: skill.primaryPath || skill.path || "",
      directory: skill.directory || "",
      duplicateCount: skill.duplicateCount || groups.get(name) || 1,
      duplicatePaths: Array.isArray(skill.duplicatePaths) ? skill.duplicatePaths : [],
      frontmatter: skill.frontmatter || parseFrontmatter(raw).data,
      lineCount: skill.lineCount || countLines(raw),
      sizeBytes: skill.sizeBytes || byteLength(raw),
      essence: skillEssence(skill, raw, description),
    };
  });
}

function mcpItems() {
  return snapshot.mcpServers.map((server, index) => {
    const name = server.name || server.id || `mcp-${index + 1}`;
    const raw = server.rawConfig || server.raw || buildMcpRaw(server);
    const endpoint = server.url || server.command || server.transport || "未记录启动方式";
    return {
      ...server,
      id: server.id || stableId(["mcp", name, server.configPath || index]),
      viewType: "mcp",
      name,
      displayName: name,
      description: endpoint,
      source: server.configType || server.ecosystem || server.transport || "config",
      category: server.category || inferCategory(name, raw, mcpCategoryRules),
      rawConfig: raw,
      primaryPath: server.configPath || "",
      enabledBool: server.enabledBool !== false && server.enabled !== false && server.enabled !== "false",
      essence: mcpEssence(server),
      sizeBytes: byteLength(raw),
    };
  });
}

function getItems() {
  return currentView === "mcp" ? mcpItems() : skillItems();
}

function skillName(skill) {
  return skill.name || skill.displayName || skill.folderName || skill.frontmatter?.name || "unknown-skill";
}

function stableId(parts) {
  return parts
    .filter((part) => part !== undefined && part !== null)
    .join("|")
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 160) || `item-${Math.random().toString(36).slice(2)}`;
}

function countBy(values) {
  const map = new Map();
  values.forEach((value) => map.set(value, (map.get(value) || 0) + 1));
  return map;
}

function inferCategory(name, text, rules) {
  const corpus = `${name}\n${text || ""}`;
  for (const [label, pattern] of rules) {
    if (pattern.test(corpus)) return label;
  }
  return "其他";
}

function skillEssence(skill, raw, description) {
  const signals = [];
  const text = `${description}\n${raw}`.toLowerCase();
  if (/use this skill|use when|trigger|applies|scope|description:/.test(text)) signals.push("触发边界");
  if (/read|inspect|official|docs?|reference|source|brief|screenshot|context/.test(text)) signals.push("知识来源");
  if (/run|execute|call|script|cli|api|tool|mcp|browser|github|figma|python|node/.test(text)) signals.push("工具路线");
  if (/must|never|avoid|do not|always|prefer|only|required|unless|ask/.test(text)) signals.push("边界约束");
  if (/validate|verify|test|lint|typecheck|build|screenshot|render|compare|evidence|proof|check/.test(text)) signals.push("验证义务");
  if (/output|deliverable|final|report|json|markdown|document|slides|export/.test(text)) signals.push("输出标准");
  const found = signals.length ? signals.join("、") : "未在快照中抽到明显控制点";
  return `局部指令包；它不是工具本身，而是在触发回合里改变模型的判断顺序。当前原文影响点：${found}。`;
}

function mcpEssence(server) {
  const endpoint = server.url ? "远程服务" : server.command ? "本地进程" : "配置入口";
  return `工具入口；它不是提示词，而是把 ${endpoint} 暴露给模型，让模型在任务需要时能调用真实能力。`;
}

function filteredItems() {
  const query = document.getElementById("searchInput").value.trim().toLowerCase();
  return getItems().filter((item) => {
    const raw = item.rawMarkdown || item.rawConfig || "";
    const haystack = [
      item.name,
      item.displayName,
      item.description,
      item.category,
      item.source,
      item.primaryPath,
      item.directory,
      raw,
    ].join("\n").toLowerCase();
    return (!query || haystack.includes(query))
      && (activeCategory === "全部" || item.category === activeCategory)
      && (activeSource === "全部" || item.source === activeSource);
  });
}

function sortedItems(items) {
  const mode = document.getElementById("sortSelect").value;
  return [...items].sort((a, b) => {
    if (mode === "category") return a.category.localeCompare(b.category, "zh-CN") || a.name.localeCompare(b.name, "zh-CN");
    if (mode === "source") return String(a.source).localeCompare(String(b.source), "zh-CN") || a.name.localeCompare(b.name, "zh-CN");
    if (mode === "size") return Number(b.sizeBytes || 0) - Number(a.sizeBytes || 0);
    return a.name.localeCompare(b.name, "zh-CN");
  });
}

function setupFilters(items) {
  const categories = ["全部", ...Array.from(new Set(items.map((item) => item.category))).sort((a, b) => a.localeCompare(b, "zh-CN"))];
  const sources = ["全部", ...Array.from(new Set(items.map((item) => item.source))).sort((a, b) => a.localeCompare(b, "zh-CN"))];
  document.getElementById("categoryFilters").innerHTML = categories.map((value) => filterRadio("category", value, value === activeCategory)).join("");
  document.getElementById("sourceFilters").innerHTML = sources.map((value) => filterRadio("source", value, value === activeSource)).join("");
  document.querySelectorAll("input[name=category]").forEach((input) => {
    input.addEventListener("change", () => {
      activeCategory = input.value;
      render();
    });
  });
  document.querySelectorAll("input[name=source]").forEach((input) => {
    input.addEventListener("change", () => {
      activeSource = input.value;
      render();
    });
  });
}

function filterRadio(name, value, checked) {
  return `<label class="check-row"><input type="radio" name="${name}" value="${escapeHtml(value)}" ${checked ? "checked" : ""}>${escapeHtml(value)}</label>`;
}

function render() {
  const skills = skillItems();
  const mcps = mcpItems();
  const items = getItems();
  applyI18n();
  setupChrome();
  setupSnapshotMeta(skills, mcps);
  setupFilters(items);

  const visible = sortedItems(filteredItems());
  document.getElementById("skillCount").textContent = skills.length;
  document.getElementById("mcpCount").textContent = mcps.length;
  document.getElementById("rawCount").textContent = skills.filter((item) => item.rawMarkdown).length;
  document.getElementById("enabledMcpCount").textContent = mcps.filter((item) => item.enabledBool).length;
  document.getElementById("resultText").textContent = `${visible.length} results | ${snapshot.generatedAt || "no snapshot time"}`;
  document.getElementById("itemRows").innerHTML = visible.map(renderRow).join("") || emptyRow();

  document.querySelectorAll(".item-row[data-id]").forEach((row) => {
    row.addEventListener("click", (event) => {
      if (event.target.closest("button")) return;
      selected[currentView] = row.dataset.id;
      renderDetail(items.find((item) => item.id === selected[currentView]));
      highlightSelected();
    });
  });
  const selectedItem = visible.find((item) => item.id === selected[currentView])
    || items.find((item) => item.id === selected[currentView])
    || visible[0];
  if (selectedItem) {
    selected[currentView] = selectedItem.id;
    renderDetail(selectedItem);
  } else {
    renderEmptyDetail();
  }
  highlightSelected();
}

function setupChrome() {
  const isMcp = currentView === "mcp";
  document.getElementById("skillsTab").classList.toggle("active", !isMcp);
  document.getElementById("mcpTab").classList.toggle("active", isMcp);
  document.getElementById("listTitle").textContent = isMcp ? t("mcpList") : t("skillList");
  document.getElementById("detailEyebrow").textContent = isMcp ? t("selectedMcp") : t("selectedSkill");
  document.getElementById("rawTitle").textContent = isMcp ? t("rawMcp") : t("rawSkill");
  document.getElementById("searchInput").placeholder = isMcp
    ? "MCP name, command, URL, config keyword"
    : "Skill name, path, description, raw text keyword";
}

function setupSnapshotMeta(skills, mcps) {
  const parts = [];
  if (snapshot.codexHome) parts.push(`Codex: ${snapshot.codexHome}`);
  if (snapshot.claudeHome) parts.push(`Claude: ${snapshot.claudeHome}`);
  if (snapshot.configPath) parts.push(`Config: ${snapshot.configPath}`);
  const title = `${skills.length} Skill / ${mcps.length} MCP`;
  document.getElementById("snapshotTitle").textContent = title;
  document.getElementById("snapshotMeta").textContent = parts.length
    ? parts.join(" | ")
    : t("snapshotHelp");

  const paths = snapshot.presetPaths && snapshot.presetPaths.length ? snapshot.presetPaths : defaultPresetPaths;
  document.getElementById("presetPaths").innerHTML = paths.slice(0, 14).map((item) => {
    const text = typeof item === "string" ? item : `${item.label || item.kind || "path"}: ${item.path || ""}`;
    return `<span class="path-chip">${escapeHtml(text)}</span>`;
  }).join("");
}

function renderRow(item) {
  const raw = item.rawMarkdown || item.rawConfig || "";
  const rawBadge = raw
    ? `<span class="badge raw">${currentView === "mcp" ? "config" : "raw"}</span>`
    : `<span class="badge warn">${currentView === "mcp" ? "no config" : "no raw"}</span>`;
  const enabledBadge = currentView === "mcp"
    ? `<span class="badge ${item.enabledBool ? "mcp" : "neutral"}">${item.enabledBool ? "enabled" : "disabled"}</span>`
    : "";
  return `
    <article class="item-row ${item.id === selected[currentView] ? "selected" : ""}" data-id="${escapeHtml(item.id)}">
      <div class="item-main">
        <strong>${escapeHtml(item.displayName || item.name)}</strong>
        <p>${escapeHtml(trimText(item.description || item.primaryPath || "no description", 160))}</p>
        <div class="item-meta">
          <span class="badge neutral">${escapeHtml(item.category)}</span>
          <span class="badge neutral">${escapeHtml(item.source)}</span>
          ${enabledBadge}
          ${rawBadge}
          ${Number(item.duplicateCount || 1) > 1 ? `<span class="badge warn">duplicate ${item.duplicateCount}</span>` : ""}
        </div>
      </div>
    </article>
  `;
}

function emptyRow() {
  return `<div class="item-row"><div class="item-main"><strong>No matches</strong><p>Adjust search, category, or source filters.</p></div></div>`;
}

function renderDetail(item) {
  if (!item) {
    renderEmptyDetail();
    return;
  }
  const isMcp = item.viewType === "mcp";
  currentDetailItem = item;
  document.getElementById("detailName").textContent = item.displayName || item.name;
  document.getElementById("detailDescription").textContent = item.description || "no description";
  document.getElementById("detailEssence").textContent = item.essence || "-";
  document.getElementById("detailCategory").textContent = item.category || "-";
  document.getElementById("detailSource").textContent = item.source || "-";
  document.getElementById("detailPath").textContent = item.primaryPath || item.directory || "-";
  document.getElementById("frontmatterSection").style.display = isMcp ? "none" : "";
  document.getElementById("frontmatterViewer").textContent = isMcp ? "-" : formatFrontmatter(item);
  updateRawViewer(item);
}

function renderEmptyDetail() {
  currentDetailItem = null;
  document.getElementById("detailName").textContent = t("noSelection");
  document.getElementById("detailDescription").textContent = t("noSelectionHelp");
  document.getElementById("detailEssence").textContent = "-";
  document.getElementById("detailCategory").textContent = "-";
  document.getElementById("detailSource").textContent = "-";
  document.getElementById("detailPath").textContent = "-";
  document.getElementById("frontmatterSection").style.display = "";
  document.getElementById("frontmatterViewer").textContent = "-";
  updateRawViewer(null);
}

function formatFrontmatter(item) {
  const frontmatter = item.frontmatter || {};
  const lines = Object.entries(frontmatter).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(", ") : value}`);
  const extras = [
    item.lineCount ? `lineCount: ${item.lineCount}` : "",
    item.sizeBytes ? `sizeBytes: ${item.sizeBytes}` : "",
    Number(item.duplicateCount || 1) > 1 ? `duplicateCount: ${item.duplicateCount}` : "",
  ].filter(Boolean);
  const duplicatePaths = item.duplicatePaths && item.duplicatePaths.length > 1
    ? ["", "duplicatePaths:", ...item.duplicatePaths.map((path) => `- ${path}`)]
    : [];
  return [...lines, ...extras, ...duplicatePaths].join("\n") || "没有 frontmatter。";
}

function missingRawMessage(isMcp) {
  if (isMcp) return "当前快照没有包含原始 MCP 配置块。可以点击“选择 MCP 配置”导入 config.toml / claude_desktop_config.json / .mcp.json。";
  return "当前快照没有包含原始 SKILL.md。请运行 `node scan-local.mjs` 重新生成，或点击“选择 Skill 目录”让浏览器读取一个目录。";
}

async function updateRawViewer(item = currentDetailItem) {
  const viewer = document.getElementById("rawViewer");
  const isMcp = item?.viewType === "mcp";
  const raw = isMcp ? item?.rawConfig : item?.rawMarkdown;
  document.getElementById("rawOriginalBtn").classList.toggle("active", rawMode === "original");
  document.getElementById("rawTranslatedBtn").classList.toggle("active", rawMode === "translated");
  document.getElementById("rawTitle").textContent = isMcp ? t("rawMcp") : t("rawSkill");

  if (!item) {
    viewer.textContent = t("noSelectionHelp");
    return;
  }

  if (!raw) {
    viewer.textContent = missingRawMessage(isMcp);
    return;
  }

  if (rawMode === "original") {
    viewer.textContent = raw;
    document.getElementById("translationStatus").textContent = t("translationStatus");
    return;
  }

  document.getElementById("translationStatus").textContent = t("translating");
  const requestId = `${item.id}:${uiLanguage}:${raw.length}`;
  viewer.dataset.translationRequest = requestId;
  const translated = await translateMarkdown(raw, uiLanguage);
  if (viewer.dataset.translationRequest === requestId) {
    viewer.textContent = translated.text;
    document.getElementById("translationStatus").textContent = t("translatedByDictionary");
  }
}

async function translateMarkdown(text, targetLanguage) {
  if (targetLanguage === "zh-CN" && hasMostlyChinese(text)) {
    return { source: "dictionary", text };
  }
  return { source: "dictionary", text: translateWithBuiltInGlossary(text, targetLanguage) };
}

function translateWithBuiltInGlossary(text, targetLanguage) {
  const replacements = glossaryFor(targetLanguage);
  return String(text || "")
    .split(/\r?\n/)
    .map((line) => translateLineWithGlossary(line, replacements))
    .join("\n");
}

function translateLineWithGlossary(line, replacements) {
  let output = line;
  for (const [from, to] of replacements) {
    output = output.replace(new RegExp(escapeRegExp(from), "gi"), to);
  }
  return output;
}

function glossaryFor(targetLanguage) {
  const base = {
    "Use this skill": {
      "zh-CN": "使用这个 Skill",
      en: "Use this Skill",
      ja: "この Skill を使用",
      ko: "이 Skill 사용",
      fr: "Utiliser ce Skill",
      de: "Diesen Skill verwenden",
      es: "Usar este Skill",
      pt: "Usar este Skill",
      ru: "Использовать этот Skill",
      ar: "استخدم هذا Skill",
    },
    "Read": {
      "zh-CN": "读取",
      en: "Read",
      ja: "読む",
      ko: "읽기",
      fr: "Lire",
      de: "Lesen",
      es: "Leer",
      pt: "Ler",
      ru: "Читать",
      ar: "اقرأ",
    },
    "Verify": {
      "zh-CN": "验证",
      en: "Verify",
      ja: "検証",
      ko: "검증",
      fr: "Vérifier",
      de: "Prüfen",
      es: "Verificar",
      pt: "Verificar",
      ru: "Проверить",
      ar: "تحقق",
    },
    "Validate": {
      "zh-CN": "验证",
      en: "Validate",
      ja: "妥当性確認",
      ko: "검증",
      fr: "Valider",
      de: "Validieren",
      es: "Validar",
      pt: "Validar",
      ru: "Валидировать",
      ar: "تحقق",
    },
    "Do not": {
      "zh-CN": "不要",
      en: "Do not",
      ja: "しない",
      ko: "하지 마세요",
      fr: "Ne pas",
      de: "Nicht",
      es: "No",
      pt: "Não",
      ru: "Не",
      ar: "لا",
    },
    "Always": {
      "zh-CN": "始终",
      en: "Always",
      ja: "常に",
      ko: "항상",
      fr: "Toujours",
      de: "Immer",
      es: "Siempre",
      pt: "Sempre",
      ru: "Всегда",
      ar: "دائما",
    },
    "Prefer": {
      "zh-CN": "优先",
      en: "Prefer",
      ja: "優先",
      ko: "우선",
      fr: "Préférer",
      de: "Bevorzugen",
      es: "Preferir",
      pt: "Preferir",
      ru: "Предпочитать",
      ar: "فضّل",
    },
    "Run": {
      "zh-CN": "运行",
      en: "Run",
      ja: "実行",
      ko: "실행",
      fr: "Exécuter",
      de: "Ausführen",
      es: "Ejecutar",
      pt: "Executar",
      ru: "Запустить",
      ar: "شغّل",
    },
    "Test": {
      "zh-CN": "测试",
      en: "Test",
      ja: "テスト",
      ko: "테스트",
      fr: "Tester",
      de: "Testen",
      es: "Probar",
      pt: "Testar",
      ru: "Тестировать",
      ar: "اختبر",
    },
    "Output": {
      "zh-CN": "输出",
      en: "Output",
      ja: "出力",
      ko: "출력",
      fr: "Sortie",
      de: "Ausgabe",
      es: "Salida",
      pt: "Saída",
      ru: "Вывод",
      ar: "مخرجات",
    },
    "触发边界": {
      "zh-CN": "触发边界",
      en: "trigger boundary",
      ja: "トリガー境界",
      ko: "트리거 경계",
      fr: "limite de déclenchement",
      de: "Auslösegrenze",
      es: "límite de activación",
      pt: "limite de acionamento",
      ru: "граница срабатывания",
      ar: "حد التشغيل",
    },
    "知识来源": {
      "zh-CN": "知识来源",
      en: "knowledge source",
      ja: "知識ソース",
      ko: "지식 출처",
      fr: "source de connaissance",
      de: "Wissensquelle",
      es: "fuente de conocimiento",
      pt: "fonte de conhecimento",
      ru: "источник знаний",
      ar: "مصدر المعرفة",
    },
    "验证义务": {
      "zh-CN": "验证义务",
      en: "validation obligation",
      ja: "検証義務",
      ko: "검증 의무",
      fr: "obligation de validation",
      de: "Validierungspflicht",
      es: "obligación de validación",
      pt: "obrigação de validação",
      ru: "обязанность проверки",
      ar: "واجب التحقق",
    },
  };

  return Object.entries(base).map(([from, translations]) => [from, translations[targetLanguage] || translations.en]);
}

function hasMostlyChinese(text) {
  const value = String(text || "");
  const chinese = (value.match(/[\u4e00-\u9fa5]/g) || []).length;
  return chinese > Math.max(8, value.length * 0.08);
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function highlightSelected() {
  document.querySelectorAll(".item-row[data-id]").forEach((row) => {
    row.classList.toggle("selected", row.dataset.id === selected[currentView]);
  });
}

function parseFrontmatter(raw) {
  const result = { data: {}, body: raw || "" };
  if (!raw || !raw.startsWith("---")) return result;
  const end = raw.indexOf("\n---", 3);
  if (end < 0) return result;
  const block = raw.slice(3, end).trim();
  result.body = raw.slice(end + 4).replace(/^\r?\n/, "");
  block.split(/\r?\n/).forEach((line) => {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) return;
    result.data[match[1]] = match[2].replace(/^["']|["']$/g, "");
  });
  return result;
}

function firstMarkdownHeading(raw) {
  const match = String(raw || "").match(/^\s{0,3}#\s+(.+)$/m);
  return match ? match[1].trim() : "";
}

function countLines(text) {
  if (!text) return 0;
  return String(text).split(/\r?\n/).length;
}

function byteLength(text) {
  return new TextEncoder().encode(String(text || "")).length;
}

function trimText(text, length) {
  const value = String(text || "");
  return value.length > length ? `${value.slice(0, length - 1)}...` : value;
}

function escapeHtml(value) {
  return String(value || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function buildMcpRaw(server) {
  const lines = [];
  if (server.configPath) lines.push(`# ${server.configPath}`);
  lines.push(`[mcp_servers.${server.name || server.id || "unknown"}]`);
  ["enabled", "command", "args", "url", "transport", "auth", "startupTimeout", "toolTimeout"].forEach((key) => {
    if (server[key] !== undefined && server[key] !== "") lines.push(`${key} = ${JSON.stringify(server[key])}`);
  });
  return lines.join("\n");
}

async function loadSnapshotFile(file) {
  const text = await file.text();
  const parsed = parseSnapshotText(text);
  snapshot = normalizeSnapshot(parsed);
  selected = { skills: "", mcp: "" };
  activeCategory = "全部";
  activeSource = "全部";
  document.getElementById("searchInput").value = "";
  render();
}

function parseSnapshotText(text) {
  const clean = String(text || "").replace(/^\uFEFF/, "").trim();
  if (clean.startsWith("window.SKILL_DATA")) {
    const json = clean
      .replace(/^window\.SKILL_DATA\s*=\s*/, "")
      .replace(/;\s*$/, "");
    return JSON.parse(json);
  }
  return JSON.parse(clean);
}

async function loadConfigFile(file) {
  const text = await file.text();
  const parsed = parseMcpConfig(text, file.name);
  snapshot = normalizeSnapshot({
    ...snapshot,
    generatedAt: new Date().toISOString(),
    configPath: file.name,
    mcpServers: parsed,
  });
  currentView = "mcp";
  selected.mcp = "";
  activeCategory = "全部";
  activeSource = "全部";
  render();
}

function parseMcpConfig(text, fileName) {
  const trimmed = String(text || "").trim();
  if (!trimmed) return [];
  if (fileName.toLowerCase().endsWith(".json") || trimmed.startsWith("{")) {
    try {
      const data = JSON.parse(trimmed);
      return extractJsonMcpServers(data, fileName);
    } catch {
      return [];
    }
  }
  return parseTomlMcpServers(trimmed, fileName);
}

function extractJsonMcpServers(data, fileName) {
  const found = [];
  walkObject(data, (value, path) => {
    if (!value || typeof value !== "object" || Array.isArray(value)) return;
    if (path[path.length - 1] !== "mcpServers") return;
    Object.entries(value).forEach(([name, config]) => {
      if (!config || typeof config !== "object") return;
      found.push({
        id: stableId(["mcp", fileName, name]),
        name,
        enabled: config.enabled === false ? "false" : "true",
        enabledBool: config.enabled !== false,
        command: config.command || "",
        args: Array.isArray(config.args) ? config.args.join(" ") : config.args || "",
        url: config.url || "",
        transport: config.url ? "remote" : config.command ? "local" : config.transport || "unknown",
        configPath: fileName,
        configType: "json",
        rawConfig: redactText(JSON.stringify({ [name]: config }, null, 2)),
      });
    });
  });
  return found;
}

function walkObject(value, visitor, path = []) {
  visitor(value, path);
  if (!value || typeof value !== "object") return;
  Object.entries(value).forEach(([key, child]) => walkObject(child, visitor, [...path, key]));
}

function parseTomlMcpServers(text, fileName) {
  const lines = text.split(/\r?\n/);
  const servers = [];
  let current = null;
  let rawLines = [];
  const finish = () => {
    if (!current) return;
    current.rawConfig = redactText(rawLines.join("\n"));
    if (!current.transport) current.transport = current.url ? "remote" : current.command ? "local" : "unknown";
    servers.push(current);
  };

  lines.forEach((line) => {
    const section = line.match(/^\s*\[(?:mcp_servers|mcpServers)\.("?)([^\]"]+)\1\]\s*$/);
    if (section) {
      finish();
      const name = section[2];
      current = {
        id: stableId(["mcp", fileName, name]),
        name,
        enabled: "true",
        enabledBool: true,
        command: "",
        args: "",
        url: "",
        transport: "",
        configPath: fileName,
        configType: "toml",
      };
      rawLines = [line];
      return;
    }
    if (line.match(/^\s*\[/)) {
      finish();
      current = null;
      rawLines = [];
      return;
    }
    if (!current) return;
    rawLines.push(line);
    const kv = line.match(/^\s*([A-Za-z0-9_-]+)\s*=\s*(.+?)\s*$/);
    if (!kv) return;
    const key = kv[1];
    const value = cleanScalar(kv[2]);
    if (key === "enabled") {
      current.enabled = value;
      current.enabledBool = value !== "false";
    } else if (key === "command" || key === "url" || key === "transport") {
      current[key] = value;
    } else if (key === "args") {
      current.args = value;
    } else if (key === "bearer_token_env_var") {
      current.auth = `env:${value}`;
    }
  });
  finish();
  return servers;
}

function cleanScalar(value) {
  return String(value || "")
    .trim()
    .replace(/^["']|["']$/g, "");
}

function redactText(text) {
  return String(text || "")
    .replace(/(access[_-]?token\s*[:=]\s*["']?)[^"'\s,}]+/gi, "$1***")
    .replace(/(api[_-]?key\s*[:=]\s*["']?)[^"'\s,}]+/gi, "$1***")
    .replace(/(secret\s*[:=]\s*["']?)[^"'\s,}]+/gi, "$1***")
    .replace(/(bearer\s+)[A-Za-z0-9._~+/=-]{12,}/gi, "$1***");
}

async function chooseSkillDirectory() {
  if (window.seeThroughDesktop?.pickSkillDirectory) {
    const data = await window.seeThroughDesktop.pickSkillDirectory();
    if (!data) return;
    snapshot = normalizeSnapshot(data);
    currentView = "skills";
    selected.skills = "";
    activeCategory = "全部";
    activeSource = "全部";
    render();
    return;
  }

  if (!window.showDirectoryPicker) {
    alert("当前浏览器不支持直接选择目录。请运行 `node scan-local.mjs` 生成快照，或导入已有 JSON/JS 快照。");
    return;
  }
  const root = await window.showDirectoryPicker({ mode: "read" });
  const skills = await readSkillsFromDirectory(root);
  snapshot = normalizeSnapshot({
    ...snapshot,
    generatedAt: new Date().toISOString(),
    skills,
    presetPaths: [`浏览器选择目录: ${root.name}`, ...defaultPresetPaths],
  });
  currentView = "skills";
  selected.skills = "";
  activeCategory = "全部";
  activeSource = "全部";
  render();
}

async function readSkillsFromDirectory(rootHandle) {
  const records = [];
  async function walk(handle, parts) {
    for await (const [name, child] of handle.entries()) {
      if (child.kind === "directory") {
        if (shouldSkipDirectory(name)) continue;
        await walk(child, [...parts, name]);
        continue;
      }
      if (child.kind !== "file" || name.toLowerCase() !== "skill.md") continue;
      const file = await child.getFile();
      const raw = await file.text();
      const directory = parts.join("/");
      const frontmatter = parseFrontmatter(raw).data;
      const skillNameFromPath = parts[parts.length - 1] || frontmatter.name || "skill";
      records.push({
        id: stableId(["browser", rootHandle.name, directory]),
        name: frontmatter.name || skillNameFromPath,
        displayName: frontmatter.name || skillNameFromPath,
        folderName: skillNameFromPath,
        source: "browser-directory",
        ecosystem: "Local",
        description: frontmatter.description || firstMarkdownHeading(raw),
        frontmatter,
        rawMarkdown: raw,
        primaryPath: `${rootHandle.name}/${directory}/SKILL.md`,
        directory: `${rootHandle.name}/${directory}`,
        lineCount: countLines(raw),
        sizeBytes: file.size,
        lastWriteTime: new Date(file.lastModified).toISOString(),
      });
    }
  }
  await walk(rootHandle, []);
  return records;
}

function shouldSkipDirectory(name) {
  return /^(node_modules|\.git|dist|build|coverage|output)$/i.test(name)
    || /^skill-quarantine/i.test(name);
}

function exportJson() {
  const payload = {
    ...snapshot,
    exportedAt: new Date().toISOString(),
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "seethrough-skill-snapshot.json";
  anchor.click();
  URL.revokeObjectURL(url);
}

async function copyRaw() {
  await copyText(document.getElementById("rawViewer").textContent || "");
  flashButton("copyRawBtn", "已复制", "复制原文");
}

async function copyText(text) {
  if (navigator.clipboard && window.isSecureContext) {
    try {
      await navigator.clipboard.writeText(text);
      return;
    } catch {
      // Fall back to the textarea route below.
    }
  }
  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.setAttribute("readonly", "");
  textarea.style.position = "fixed";
  textarea.style.left = "-9999px";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}

function flashButton(id, text, original) {
  const button = document.getElementById(id);
  button.textContent = text;
  window.setTimeout(() => {
    button.textContent = original;
  }, 1200);
}

function switchView(view) {
  currentView = view;
  activeCategory = "全部";
  activeSource = "全部";
  document.getElementById("searchInput").value = "";
  render();
}

async function bootstrap() {
  applyI18n();
  if (window.seeThroughDesktop?.scanLocal) {
    try {
      snapshot = normalizeSnapshot(await window.seeThroughDesktop.scanLocal({}));
    } catch (error) {
      console.error(error);
    }
  } else if (!window.SKILL_DATA) {
    await tryLoadSnapshotScript();
  }
  if (window.SKILL_DATA) snapshot = normalizeSnapshot(window.SKILL_DATA);
  render();
}

function tryLoadSnapshotScript() {
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = "./skills-data.js";
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.head.appendChild(script);
  });
}

document.getElementById("searchInput").addEventListener("input", render);
document.getElementById("sortSelect").addEventListener("change", render);
document.getElementById("exportBtn").addEventListener("click", exportJson);
document.getElementById("copyRawBtn").addEventListener("click", copyRaw);
document.getElementById("languageSelect").addEventListener("change", (event) => {
  uiLanguage = event.target.value;
  localStorage.setItem("seethrough-skill:language", uiLanguage);
  applyI18n();
  render();
});
document.getElementById("rawOriginalBtn").addEventListener("click", () => {
  rawMode = "original";
  updateRawViewer();
});
document.getElementById("rawTranslatedBtn").addEventListener("click", () => {
  rawMode = "translated";
  updateRawViewer();
});
document.getElementById("loadSnapshotBtn").addEventListener("click", () => document.getElementById("snapshotInput").click());
document.getElementById("loadConfigBtn").addEventListener("click", async () => {
  if (window.seeThroughDesktop?.pickMcpConfig) {
    const data = await window.seeThroughDesktop.pickMcpConfig();
    if (data) {
      snapshot = normalizeSnapshot(data);
      currentView = "mcp";
      selected.mcp = "";
      render();
    }
    return;
  }
  document.getElementById("configInput").click();
});
document.getElementById("chooseDirectoryBtn").addEventListener("click", () => chooseSkillDirectory().catch((error) => {
  console.error(error);
  alert(`读取目录失败：${error.message || error}`);
}));
document.getElementById("snapshotInput").addEventListener("change", (event) => {
  const file = event.target.files && event.target.files[0];
  if (file) loadSnapshotFile(file).catch((error) => alert(`导入快照失败：${error.message || error}`));
  event.target.value = "";
});
document.getElementById("configInput").addEventListener("change", (event) => {
  const file = event.target.files && event.target.files[0];
  if (file) loadConfigFile(file).catch((error) => alert(`导入配置失败：${error.message || error}`));
  event.target.value = "";
});
document.querySelectorAll(".view-tabs button").forEach((button) => {
  button.addEventListener("click", () => switchView(button.dataset.view));
});

bootstrap();
